# Generated by Django 2.0.4 on 2018-04-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=150)),
                ('Sub_Heading', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Sub_Title', models.CharField(max_length=150)),
                ('Banner_Photo', models.ImageField(upload_to='static/media')),
                ('Body', models.TextField()),
                ('Author', models.CharField(max_length=150)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Date_modified', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(blank=True, choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Hidden', 'Hidden')], default=True, max_length=6)),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tags'),
        ),
    ]
