# Generated by Django 2.0.4 on 2018-04-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180417_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('sub_Heading', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Banner_Photo',
            new_name='banner_Photo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Date_modified',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Sub_Title',
            new_name='sub_Title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Blog',
        ),
        migrations.AlterField(
            model_name='post',
            name='Status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('draft', 'Draft'), ('hidden', 'Hidden')], default=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='Tags', to='blog.Post'),
        ),
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Index'),
            preserve_default=False,
        ),
    ]
