# Generated by Django 2.0.4 on 2018-04-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180418_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='sub_Heading',
            new_name='sub_heading',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='banner_Photo',
            new_name='banner_photo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='Post', to='blog.Tags'),
        ),
    ]
